### ISSUE TITLE
[Champ-Animation] Jax

### ISSUE THREAD

**Issue by jason-r-taylor** [nicolasdeory/leagueoflegends-led#15]

**Comment by jason-r-taylor** [comment]
I created the animations with the tool, but dont have a way to test them. I cant get the project to build on my system

**Comment by nicolasdeory** [comment]
If you want me to test them, you could create a pull request adding the animations to `Animations/LeagueOfLegends/Champions/Jax`. As to why it's not building, what errors are you getting? I suspect it probably complains about the razer chroma api DLL

**Comment by jason-r-taylor** [comment]
I can do a PR, for now here are the errors I'm seeing. I tried building inside both VS and Jetbrains Rider

 RazerChromaController.cs(1, 7): [CS0246] The type or namespace name 'RazerChroma' could not be found (are you missing a using directive or an assembly reference?)
  RazerChromaController.cs(2, 7): [CS0246] The type or namespace name 'RazerChromaFrameEngine' could not be found (are you missing a using directive or an assembly reference?)
  RazerChromaController.cs(10, 14): [CS0246] The type or namespace name 'RazerChroma' could not be found (are you missing a using directive or an assembly reference?)
  RazerChromaController.cs(28, 17): [CS0246] The type or namespace name 'KeyboradFrame' could not be found (are you missing a using directive or an assembly reference?)
  RazerChromaController.cs(29, 17): [CS0246] The type or namespace name 'NativeRazerApi' could not be found (are you missing a using directive or an assembly reference?)
  RazerChromaController.cs(142, 16): [CS0246] The type or namespace name 'RzKey' could not be found (are you missing a using directive or an assembly reference?)
  RazerChromaController.cs(191, 16): [CS0246] The type or namespace name 'RzKey' could not be found (are you missing a using directive or an assembly reference?)

**Comment by nicolasdeory** [comment]
That's what I suspected. My bad. I've just included the Razer Chroma dependency in the dev branch, you should be able to build now.
