### ISSUE TITLE
Animations don't always trigger.

### ISSUE THREAD

**Issue by besio** [nicolasdeory/leagueoflegends-led#24]
I don't know if this is a Razer Synapse 3 issue or this app but animations not always are appearing after triggering them.
f.e if I'm using an ability once, the animation is casting well, but the second cast doesn't trigger animation as well as next attempts. I have used redemption many times in a game, but its animation was triggered in one-fifth of the number of attempts. 
If the rest of you have no problems with this, I will try to reinstall Razer Synapse and/or keyboard in the device manager.
Keep doing your work! x

**Comment by besio** [comment]
I will try to update videos.

**Comment by besio** [comment]
https://youtu.be/DDE2EuSaPOw
i hope it'll work

**Comment by nicolasdeory** [comment]
Thanks for the video! That seems to be because you're on practice mode. Animations don't trigger if the ability is on cooldown, but since you're on practice mode, you don't have any cooldowns.

However, implementing URF / Practice detection would be useful.

**Comment by besio** [comment]
@nicolasdeory so cooldowns are taken from the numbers given by ability levels (f.e. an ability has 10 sec cooldown on its 3rd level, so the animation can't occur earlier than these 10 sec?) does it involve cooldown reduction?

**Comment by nicolasdeory** [comment]
Yes, it takes CR into account.

**Comment by besio** [comment]
okay, i'm closing this issue!
