### ISSUE TITLE
 I would like to know how to make this incredible function work. Someone help me?

### ISSUE THREAD

**Issue by Minibomba2** [nicolasdeory/leagueoflegends-led#31]
I have downloaded the files and tried to run the program but it does nothing

**Comment by bwiethorn** [comment]
same problem

**Comment by XxMixkillerxX** [comment]
me too

**Comment by nicolasdeory** [comment]
Please, try the latest v0.4.1pre release, and tell me if it works for you.

**Comment by Zonsor** [comment]
The basic function in latest version "v0.4.1pre" works for me, but champions' abilities don't. Or I don't know how to set this function.

**Comment by nicolasdeory** [comment]
@Zonsor Make sure you're playing one of the supported champions, such as Vel'Koz, Ahri, Udyr, Twisted Fate, or Ezreal.

**Comment by Zonsor** [comment]
@nicolasdeory  Yeah! I have tried  Vel'Koz, Ahri, and Ezreal

**Comment by nicolasdeory** [comment]
@Zonsor And their animations aren't playing?

**Comment by Zonsor** [comment]
@nicolasdeory Yes, do I need to do some setting for champion's ability

**Comment by Bennobear** [comment]
What do i need to setup in synapse? 
Because it's just using my Chroma Studio settings

**Comment by 007agent30** [comment]
Extract the zip file and the open V0.4.0b.zip/Release/netcoreapp3.0/LedDashboard.exe. it might also be V0.4.0b.zip/Release/netcoreapp3.0/win-x64/LedDashboard.exe. and then it will automatically be set up ^^
