### ISSUE TITLE
Invalid comma here.

### ISSUE THREAD

**Issue by randycarrero** [nicolasdeory/leagueoflegends-led#47]
https://github.com/nicolasdeory/leagueoflegends-led/blob/ec73b98107f3aefeec545ca14e176c2c2dd01b33/LedDashboardCore/Resources/keyboardLayout.json#L393

Code should be      
"key":"^",
        "x":340,
        `"y":80`
    },

saw that error. I'm trying to get a grey scale set up before game starts on the program. so people can see how it looks before hand. still thinking of adding a visual keyboard set up. but for now just buttons grey scale before game starts.

**Comment by nicolasdeory** [comment]
What do you mean by gray scale? The keyboard should already light up when the game is loading. I should add a setting to test if the integration is working without having to open the game, though.

**Comment by randycarrero** [comment]
yes that's correct. you see the visual once the game is started. i was making a gray version for when the game is not loading and you are waiting for the next one. nothing major just a preference.
