### ISSUE TITLE
I downloaded the lighting file, I don’t know how to use it for razer connect

### ISSUE THREAD

**Issue by offthestage** [nicolasdeory/leagueoflegends-led#48]
I downloaded the lighting file, I don’t know how to use it for razer connect.Don't know how to import files

**Comment by randycarrero** [comment]
This portion shows you how to use the LED lights. once open make sure you have razer open as well and razer connect should auto place the LED lights. 
https://github.com/nicolasdeory/leagueoflegends-led#usage
