### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by azazel795** [nicolasdeory/leagueoflegends-led#68]
Hello! when i double click LedDashboard.exe a get an error message: "Error initializing Razer Chroma controller. Is Razer Synapse installed? Status = 6023" i press ok and then nothing. I have synapse 3 installed and chroma studio works fine.

**Comment by azazel795** [comment]
Ok! made it work it was chroma connect problem! thenks for the great work. Plz make some more ADC champs. thnaks

**Comment by pallaxx** [comment]
Hi, i have the same error code, how you fix that?

**Comment by Brooeli** [comment]
I have the same issue, how did you solve yours?
